/* Generated By:JavaCC: Do not edit this line. ExpressionParserTreeConstants.java Version 5.0 */
package com.alipay.android.core.expapp.api.impl;

public interface ExpressionParserTreeConstants
{
  public int JJTBLOCK = 0;
  public int JJTFUNCTION = 1;
  public int JJTARGUMENTLIST = 2;
  public int JJTLITERAL = 3;


  public String[] jjtNodeName = {
    "Block",
    "Function",
    "ArgumentList",
    "Literal",
  };
}
/* JavaCC - OriginalChecksum=3e4961dd18384a6d0a11c8b359ac11f6 (do not edit this line) */
